package com.raphael.springbootvalidation.constants;

public enum Gender {

    MALE,
    FEMALE,
    NON_BINARY,
    GENDERQUEER,
    GENDERFLUID,
    AGENDER,
    BIGENDER,
    TWO_SPIRIT,
    ANDROGYNOUS,
    DEMIGENDER,
    NEUTROIS,
    GENDER_QUESTIONING,
    GENDER_NONCONFORMING,
    TRANSGENDER,
    TRANSMASCULINE,
    TRANSFEMININE,
    CISGENDER,
    INTERSEX,
    PANGENDER,
    GENDER_VARIANT,
    GENDER_EXPANSIVE,
    GENDER_CREATIVE,
    THIRD_GENDER,
    OTHER,
    PREFER_NOT_TO_SAY

}
